In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.decomposition import PCA
import plotly.express as px

In [2]:
TFIDF_L2 = pd.read_csv("TFIDF_L2.csv", sep="|", index_col=0)
LIB = pd.read_csv("LIB.csv", sep="|", index_col=0)

# PCA Components (4)

In [3]:
pca_engine = PCA(n_components=10)

X_pca = pca_engine.fit_transform(TFIDF_L2)

COMPONENTS = pd.DataFrame(
    pca_engine.components_,
    columns=TFIDF_L2.columns,
    index=[f'PC{i}' for i in range(pca_engine.n_components_)]
)
COMPONENTS

,0,00,000,00000,000s,004,005,006,007,008,...,zub,zuboomboom,zucchinis,zurich,zuse,zuzu,zwrotka,zwycizc,zyska,zz
PC0,-0.000635,0.004824,0.000112,0.000226,-0.000096,0.000047,0.001057,0.001383,0.001114,0.003058,...,0.000201,-0.000080,0.001077,0.000223,-0.000317,0.000156,0.000320,0.000160,0.000160,0.000117
PC1,0.000242,-0.001628,-0.000170,-0.000173,-0.000019,-0.000325,-0.000183,0.000203,-0.001062,-0.001369,...,-0.000108,0.000042,-0.000228,-0.000135,0.000393,0.000118,-0.000179,-0.000089,-0.000089,0.000138
PC2,0.003942,-0.000297,0.000819,-0.000028,0.000102,-0.000536,-0.000416,-0.000025,-0.000575,-0.000474,...,0.000011,0.000104,0.000571,0.000038,0.000811,0.000020,0.000083,0.000042,0.000042,0.001211
PC3,0.004832,0.000995,0.000108,0.000018,-0.000051,-0.000163,-0.000111,0.000046,-0.000004,0.000261,...,0.000106,0.000200,0.000753,0.000103,0.000894,0.000077,0.000155,0.000078,0.000078,0.001515
PC4,-0.004852,0.001618,0.000202,0.000005,-0.000180,-0.000305,-0.000333,-0.000037,-0.000187,-0.000117,...,0.000186,-0.000095,0.000845,0.000032,-0.000137,0.000055,0.000050,0.000025,0.000025,-0.000009
PC5,-0.000854,0.001676,-0.000482,0.000065,-0.000195,-0.000003,-0.000114,-0.000067,0.000047,0.000046,...,0.000041,-0.000073,0.000024,0.000041,-0.000585,0.000212,0.000046,0.000023,0.000023,-0.001223
PC6,0.010454,0.000079,-0.002331,0.000049,-0.000135,0.000560,-0.000074,0.000062,0.001019,0.001417,...,0.000091,0.000014,0.001715,0.000070,0.000817,-0.000055,0.000089,0.000044,0.000044,0.000096
PC7,-0.000924,0.002684,0.001144,0.000029,-0.000251,-0.000546,-0.000454,0.000087,-0.000363,-0.000212,...,-0.000014,-0.000164,0.000165,0.000034,0.000228,-0.000026,0.000050,0.000025,0.000025,-0.000027
PC8,-0.008566,0.000694,0.001831,0.000007,0.000275,0.000121,-0.000351,0.000172,0.000259,0.000403,...,0.000022,-0.000103,-0.000815,-0.000047,0.000083,-0.000101,0.000007,0.000003,0.000003,0.001134
PC9,-0.002618,0.000181,-0.000885,0.000088,-0.000138,-0.000207,-0.000012,-0.000366,-0.000235,-0.000561,...,0.000076,0.000307,-0.000321,0.000020,0.000279,-0.000062,0.000100,0.000050,0.000050,0.000941

In [12]:
COMPONENTS.loc['PC0'].sort_values(ascending=False).head(5)

term_str
la            0.481741
california    0.062577
eh            0.053404
christmas     0.048190
shine         0.047489
Name: PC0, dtype: float64

In [13]:
COMPONENTS.loc['PC1'].sort_values().head(5)

term_str
ocean        -0.058140
eyes         -0.038207
shine        -0.037218
california   -0.035144
soon         -0.033382
Name: PC1, dtype: float64

In [6]:
COMPONENTS.to_csv("/Users/natalieseah/Desktop/TextasData/PCA_COMPONENTS.csv", sep="|")

# PCA DCM (4)

In [7]:
DCM = pd.DataFrame(
    X_pca,
    index=TFIDF_L2.index,
    columns=[f'PC{i}' for i in range(X_pca.shape[1])]
)
DCM

,PC0,PC1,PC2,PC3,PC4,PC5,PC6,PC7,PC8,PC9
song_id,,,,,,,,,,
0,0.029258,-0.013776,0.025163,0.031891,0.015020,-0.016187,0.047335,0.019902,0.009566,-0.020230
1,-0.083672,0.080797,0.097768,0.119711,-0.021958,0.049645,0.058817,-0.043389,-0.001270,-0.061300
2,-0.095949,0.061577,0.044773,0.033054,0.035096,-0.004267,0.084677,0.060169,-0.013518,-0.033335
3,-0.080361,0.094181,0.046251,0.134266,0.069097,0.072695,-0.091023,0.117872,0.089746,0.018998
4,0.030577,-0.004123,0.039570,0.050051,-0.007245,-0.008402,0.029094,0.020933,-0.002408,-0.004300
...,...,...,...,...,...,...,...,...,...,...
4110,-0.022707,-0.035149,-0.075996,-0.077155,-0.036805,-0.034540,0.004004,-0.012178,0.028455,-0.132715
4111,0.063686,-0.047646,-0.005867,-0.001065,0.021418,0.005327,-0.005284,0.018932,-0.032621,0.032851
4112,0.056663,-0.026841,0.026713,0.037995,0.007684,0.004730,0.020143,0.026466,-0.004187,0.024420
4113,0.091294,-0.043804,0.018429,0.033113,0.010439,0.008864,0.016449,0.009064,0.001336,0.016462
4114,0.042962,-0.038173,0.003932,-0.009426,0.000621,0.009957,0.000059,0.009919,-0.002452,0.002606

In [8]:
DCM.to_csv("/Users/natalieseah/Desktop/TextasData/PCA_DCM.csv", sep="|")

# PCA Loadings (4)

In [9]:
LOADINGS = pd.DataFrame(
    pca_engine.components_.T * np.sqrt(pca_engine.explained_variance_),
    index=TFIDF_L2.columns,
    columns=[f'PC{i}' for i in range(pca_engine.n_components_)]
)

LOADINGS.index.name = 'term_str'

LOADINGS

,PC0,PC1,PC2,PC3,PC4,PC5,PC6,PC7,PC8,PC9
term_str,,,,,,,,,,
0,-0.000048,0.000017,0.000259,0.000313,-3.063284e-04,-0.000053,0.000628,-0.000054,-4.970067e-04,-0.000150
00,0.000362,-0.000113,-0.000020,0.000064,1.021829e-04,0.000103,0.000005,0.000158,4.024262e-05,0.000010
000,0.000008,-0.000012,0.000054,0.000007,1.275538e-05,-0.000030,-0.000140,0.000067,1.062403e-04,-0.000051
00000,0.000017,-0.000012,-0.000002,0.000001,3.329104e-07,0.000004,0.000003,0.000002,4.263747e-07,0.000005
000s,-0.000007,-0.000001,0.000007,-0.000003,-1.134801e-05,-0.000012,-0.000008,-0.000015,1.597576e-05,-0.000008
...,...,...,...,...,...,...,...,...,...,...
zuzu,0.000012,0.000008,0.000001,0.000005,3.464070e-06,0.000013,-0.000003,-0.000002,-5.851535e-06,-0.000004
zwrotka,0.000024,-0.000012,0.000005,0.000010,3.180353e-06,0.000003,0.000005,0.000003,3.940566e-07,0.000006
zwycizc,0.000012,-0.000006,0.000003,0.000005,1.590177e-06,0.000001,0.000003,0.000001,1.970283e-07,0.000003
zyska,0.000012,-0.000006,0.000003,0.000005,1.590177e-06,0.000001,0.000003,0.000001,1.970283e-07,0.000003
zz,0.000009,0.000010,0.000080,0.000098,-5.913898e-07,-0.000075,0.000006,-0.000002,6.579931e-05,0.000054

In [10]:
LOADINGS.to_csv("/Users/natalieseah/Desktop/TextasData/PCA_LOADINGS.csv", sep="|")

# PCA Visualization 1

In [15]:
# Join with LIB to get artist labels
DCM_LABELED = DCM.join(LIB[['Artist', 'Title']])

# Documents scatterplot
fig = px.scatter(
    DCM_LABELED,
    x='PC0',
    y='PC1',
    color='Artist',
    hover_name='Title',
    hover_data={'Artist': True, 'PC0': False, 'PC1': False},
    title='Documents in PC0 x PC1 Space (colored by Artist)',
    height=800,
    opacity=0.6
)
fig.show()

# Loadings scatterplot
COMPS_RESET = COMPONENTS.T.reset_index()
COMPS_RESET.columns.name = None
COMPS_RESET = COMPS_RESET.rename(columns={'index': 'term_str'})

fig2 = px.scatter(
    COMPS_RESET,
    x='PC0',
    y='PC1',
    hover_name='term_str',
    title='Loadings in PC0 x PC1 Space',
    height=800,
    opacity=0.4
)
fig2.show()

# PCA Visualization 2

In [ ]:
# Documents scatterplot
fig = px.scatter(
    DCM_LABELED,
    x='PC1',
    y='PC2',
    color='Artist',
    hover_name='Title',
    hover_data={'Artist': True, 'PC1': False, 'PC2': False},
    title='Documents in PC1 x PC2 Space (colored by Artist)',
    height=800,
    opacity=0.6
)
fig.show()

# Loadings scatterplot
fig2 = px.scatter(
    COMPS_RESET,
    x='PC1',
    y='PC2',
    hover_name='term_str',
    title='Loadings in PC1 x PC2 Space',
    height=800,
    opacity=0.4
)
fig2.show()