In [33]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.decomposition import PCA
import plotly.express as px

In [34]:
TFIDF_L2 = pd.read_csv("TFIDF_L2.csv", sep="|", index_col=0)
LIB = pd.read_csv("LIB.csv", sep="|", index_col=0)

# PCA Components (4)

In [35]:
pca_engine = PCA(n_components=10)

X_pca = pca_engine.fit_transform(TFIDF_L2)

COMPONENTS = pd.DataFrame(
    pca_engine.components_,
    columns=TFIDF_L2.columns,
    index=[f'PC{i}' for i in range(pca_engine.n_components_)]
)
COMPONENTS

,0,00,000,00000,000s,004,005,006,007,008,...,zub,zuboomboom,zucchinis,zurich,zuse,zuzu,zwrotka,zwycizc,zyska,zz
PC0,-0.000584,0.004839,0.000103,0.000224,-0.000096,0.000046,0.001057,0.001379,0.001110,0.003049,...,0.000201,-0.000082,0.001073,0.000222,-0.000311,0.000156,0.000319,0.000160,0.000160,0.000129
PC1,0.000258,-0.001609,-0.000245,-0.000176,-0.000016,-0.000319,-0.000179,0.000194,-0.001061,-0.001382,...,-0.000108,0.000040,-0.000277,-0.000136,0.000400,0.000117,-0.000180,-0.000090,-0.000090,0.000139
PC2,0.003459,-0.000204,0.000622,-0.000040,0.000106,-0.000533,-0.000463,-0.000055,-0.000576,-0.000509,...,0.000008,0.000073,0.000670,0.000034,0.000843,0.000025,0.000075,0.000038,0.000038,0.001280
PC3,0.004237,0.000899,0.000072,0.000021,-0.000054,-0.000178,-0.000098,0.000050,-0.000035,0.000227,...,0.000104,0.000233,0.000709,0.000102,0.000858,0.000078,0.000150,0.000075,0.000075,0.001495
PC4,-0.004169,0.001492,0.000434,0.000006,-0.000171,-0.000327,-0.000273,-0.000009,-0.000159,-0.000045,...,0.000183,-0.000065,0.000519,0.000034,-0.000163,0.000049,0.000049,0.000024,0.000024,0.000037
PC5,-0.000720,0.001074,0.000023,0.000070,-0.000236,-0.000130,-0.000195,-0.000051,-0.000092,-0.000111,...,0.000040,0.000015,0.000191,0.000040,-0.000613,0.000175,0.000044,0.000022,0.000022,-0.001358
PC6,0.012039,0.000750,-0.002190,0.000055,-0.000156,0.000566,0.000007,0.000083,0.001024,0.001451,...,0.000093,-0.000022,0.001034,0.000077,0.000908,-0.000026,0.000091,0.000046,0.000046,0.000239
PC7,-0.002565,0.002747,0.001585,0.000046,-0.000225,-0.000418,-0.000378,0.000119,-0.000066,0.000161,...,-0.000009,-0.000135,-0.000475,0.000045,0.000260,-0.000062,0.000062,0.000031,0.000031,0.000014
PC8,-0.005808,-0.000205,0.001020,0.000011,0.000326,-0.000060,-0.000683,0.000101,0.000099,0.000234,...,0.000045,-0.000149,-0.000538,-0.000040,0.000126,-0.000102,0.000027,0.000013,0.000013,0.001465
PC9,-0.005153,0.000681,0.000397,0.000072,-0.000101,0.000112,0.000201,-0.000209,0.000104,-0.000136,...,0.000076,0.000071,-0.000354,0.000027,0.000047,-0.000045,0.000086,0.000043,0.000043,0.001004

In [36]:
COMPONENTS.loc['PC1'].sort_values(ascending=False).head(5)

la      0.807984
yeah    0.234369
baby    0.157376
girl    0.126921
want    0.122399
Name: PC1, dtype: float64

In [37]:
COMPONENTS.loc['PC2'].sort_values().head(5)

one     -0.280808
rules   -0.272992
count   -0.270196
em      -0.212125
la      -0.189480
Name: PC2, dtype: float64

In [38]:
COMPONENTS.to_csv("/Users/natalieseah/Desktop/TextasData/PCA_COMPONENTS.csv", sep="|")

# PCA DCM (4)

In [39]:
DCM = pd.DataFrame(
    X_pca,
    index=TFIDF_L2.index,
    columns=[f'PC{i}' for i in range(X_pca.shape[1])]
)
DCM

,PC0,PC1,PC2,PC3,PC4,PC5,PC6,PC7,PC8,PC9
song_id,,,,,,,,,,
0,0.029437,-0.013914,0.027252,0.029466,0.011160,-0.019511,0.050110,0.019875,-0.000446,-0.005510
1,-0.083316,0.081012,0.103305,0.120384,-0.025126,0.044797,0.055716,-0.047116,0.008692,-0.067013
2,-0.096480,0.060947,0.046394,0.032781,0.032982,-0.010245,0.082968,0.054857,-0.021434,-0.030067
3,-0.080062,0.093477,0.053880,0.125128,0.043459,0.055306,-0.064184,0.100891,0.027180,0.069930
4,0.030565,-0.004125,0.040349,0.049087,-0.009300,-0.010227,0.028027,0.017308,-0.005042,-0.000428
...,...,...,...,...,...,...,...,...,...,...
4110,-0.022854,-0.035983,-0.076209,-0.068441,-0.034024,-0.039032,-0.015452,0.010057,-0.021595,-0.129778
4111,0.063598,-0.047737,-0.006965,-0.000723,0.023146,0.004108,-0.002265,0.013913,-0.037238,0.028593
4112,0.056623,-0.026785,0.027209,0.035926,0.005865,0.005455,0.017509,0.030088,-0.006705,0.026851
4113,0.091191,-0.044060,0.017276,0.032379,0.009908,0.008593,0.016878,0.010802,0.003183,0.014508
4114,0.043008,-0.037979,0.004434,-0.009536,0.001190,0.008394,-0.000471,0.010511,-0.001342,0.004191

In [40]:
DCM.to_csv("/Users/natalieseah/Desktop/TextasData/PCA_DCM.csv", sep="|")

# PCA Loadings (4)

In [41]:
LOADINGS = pd.DataFrame(
    pca_engine.components_.T * np.sqrt(pca_engine.explained_variance_),
    index=TFIDF_L2.columns,
    columns=[f'PC{i}' for i in range(pca_engine.n_components_)]
)

LOADINGS.index.name = 'term_str'

LOADINGS

,PC0,PC1,PC2,PC3,PC4,PC5,PC6,PC7,PC8,PC9
term_str,,,,,,,,,,
0,-0.000044,0.000018,0.000227,0.000274,-2.633652e-04,-0.000044,0.000723,-1.508128e-04,-3.355593e-04,-0.000296
00,0.000363,-0.000112,-0.000013,0.000058,9.426156e-05,0.000066,0.000045,1.615248e-04,-1.182521e-05,0.000039
000,0.000008,-0.000017,0.000041,0.000005,2.741687e-05,0.000001,-0.000132,9.319152e-05,5.893099e-05,0.000023
00000,0.000017,-0.000012,-0.000003,0.000001,3.756292e-07,0.000004,0.000003,2.688833e-06,6.612342e-07,0.000004
000s,-0.000007,-0.000001,0.000007,-0.000003,-1.077753e-05,-0.000015,-0.000009,-1.322522e-05,1.881972e-05,-0.000006
...,...,...,...,...,...,...,...,...,...,...
zuzu,0.000012,0.000008,0.000002,0.000005,3.081852e-06,0.000011,-0.000002,-3.625857e-06,-5.867519e-06,-0.000003
zwrotka,0.000024,-0.000013,0.000005,0.000010,3.065761e-06,0.000003,0.000005,3.642959e-06,1.545352e-06,0.000005
zwycizc,0.000012,-0.000006,0.000002,0.000005,1.532880e-06,0.000001,0.000003,1.821479e-06,7.726758e-07,0.000002
zyska,0.000012,-0.000006,0.000002,0.000005,1.532880e-06,0.000001,0.000003,1.821479e-06,7.726758e-07,0.000002
zz,0.000010,0.000010,0.000084,0.000097,2.316337e-06,-0.000084,0.000014,8.454015e-07,8.463119e-05,0.000058

In [42]:
LOADINGS.to_csv("/Users/natalieseah/Desktop/TextasData/PCA_LOADINGS.csv", sep="|")

# PCA Visualization 1

In [43]:
# Join with LIB to get artist labels
DCM_LABELED = DCM.join(LIB[['Artist', 'Title']])

# Documents scatterplot
fig = px.scatter(
    DCM_LABELED,
    x='PC0',
    y='PC1',
    color='Artist',
    hover_name='Title',
    hover_data={'Artist': True, 'PC0': False, 'PC1': False},
    title='Documents in PC0 x PC1 Space (colored by Artist)',
    height=800,
    opacity=0.6
)
fig.show()

# Loadings scatterplot
COMPS_RESET = COMPS.reset_index()

fig2 = px.scatter(
    COMPS_RESET,
    x='PC0',
    y='PC1',
    hover_name='term_str',
    title='Loadings in PC0 x PC1 Space',
    height=800,
    opacity=0.4
)
fig2.show()

# PCA Visualization 2

In [44]:
# Documents scatterplot
fig = px.scatter(
    DCM_LABELED,
    x='PC1',
    y='PC2',
    color='Artist',
    hover_name='Title',
    hover_data={'Artist': True, 'PC1': False, 'PC2': False},
    title='Documents in PC1 x PC2 Space (colored by Artist)',
    height=800,
    opacity=0.6
)
fig.show()

# Loadings scatterplot
fig2 = px.scatter(
    COMPS_RESET,
    x='PC1',
    y='PC2',
    hover_name='term_str',
    title='Loadings in PC1 x PC2 Space',
    height=800,
    opacity=0.4
)
fig2.show()